CharlesdevBookmark System Enhancement
BU-Spark/se-bch-als-resource-app pull request #76
Opened 2024-10-26 23:57 UTC by Charles-Zhang-114514

## Main Features Added
1. Folder Management System
   - Added support for custom bookmark folders
   - Implemented folder creation functionality
   - Added folder renaming capability

2. User Interface Improvements
   - Redesigned bookmark listing page to show folder structure
   - Added intuitive folder navigation
   - Maintained consistent UI style with existing design

3. Functionality Enhancements
   - Added folder-specific bookmark management
   - Implemented folder-level operations (clear, rename)
   - Maintained existing bookmark sharing functionality

## Technical Implementations
1. Updated Components:
   - BookmarkContext.tsx: Added folder management logic
   - BookmarkButton.tsx: Added folder selection modal
   - [folderId].tsx: New component for folder detail view
   - ResourcesHandouts.tsx: Enhanced to support folder-specific views

2. Data Management:
   - Extended localStorage implementation for folder support
   - Maintained existing bookmark data structure
   - Added new folder data structure
   - Implemented data consistency checks

## Testing
- Verified folder creation and management
- Tested bookmark organization across folders
- Confirmed sharing functionality works with folder system
- Validated UI responsiveness and consistency

Demo: https://github.com/user-attachments/assets/d894258e-cffd-4ce1-af3f-64327b98fe38

2024-10-27 12:48 UTC, mochiakku requested changes
Also we want to merge into the dev branch, not main, could you change that?

2024-10-27 12:48 UTC, mochiakku commented on code/src/styles/Bookmark.module.css
Could you remove the comments in chinese?

2024-10-27 12:48 UTC, mochiakku commented
But besides that looks good! We definitely need to work on the styling but for now is good

2024-10-28 14:08 UTC, mochiakku commented
Also, is there any way to create a new folder from the bookmark's page? Or are we only allowed to do that when we add a resource to a bookmark?

2024-10-28 22:05 UTC, Charles-Zhang-114514 commented
> Also, is there any way to create a new folder from the bookmark's page? Or are we only allowed to do that when we add a resource to a bookmark?

Hi, I will try tonight

2024-10-28 22:06 UTC, Charles-Zhang-114514 commented
> Also we want to merge into the dev branch, not main, could you change that?

OK, I have changed.

2024-10-30 12:49 UTC, mochiakku approved these changes

2024-10-30 12:51 UTC, mochiakku commented
Looks good, be aware of the conflict before merging and I'll look into why the deployments are failing

2024-10-30 16:02 UTC, Charles-Zhang-114514 commented
> Looks good, be aware of the conflict before merging and I'll look into why the deployments are failing

Thank you, and if there is any problem, please let me know asap.

2024-11-06 02:31 UTC, mochiakku approved these changes

2024-11-06 03:21 UTC, DarianC26 approved these changes

2024-11-06 03:21 UTC, merged